name: Build

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "*" ]

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: Pull images
        run: docker-compose pull
      - name: Build and test
        run: |
          docker-compose build accountlib
          docker-compose run accountlib
